workflows:
  ios-workflow:
    name: iOS Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter Bağımlılıklarını Yükle
        script: |
          flutter pub get
      - name: iOS Yapılandırma Dosyalarını Oluştur (Zorunlu)
        script: |
          # Windows'ta oluşmayan podhelper.rb dosyasını Mac sunucusunda oluşturur
          flutter build ios --config-only
      - name: CocoaPods Kurulumu (Temiz Build)
        script: |
          cd ios
          rm -rf Podfile.lock Pods
          pod install --repo-update
          cd ..
      - name: iOS IPA Build
        script: |
          # --debug yerine --release kullanarak boyutu düşürür ve performansı artırırız
          flutter build ipa --release --export-options-plist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - senin-eposta-adresin@example.com