workflows:
  ios-workflow:
    name: Uluslararasi Alevi Vakfi iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: alevi-vakfi 
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter Paketlerini Yukle
        script: |
          flutter pub get
      - name: Apple Sertifikalarini ve Profillerini Yapilandir
        script: |
          # HATANIN ÇÖZÜMÜ: Bu komut export_options.plist dosyasını oluşturur
          xcode-project use-profiles
      - name: iOS Yapilandirma Dosyalarini Olustur (Kritik Adim)
        script: |
          # Sertifika hatası almadan podhelper.rb dosyasını oluşturur
          flutter build ios --config-only --no-codesign
      - name: CocoaPods Kurulumu (Temiz Build)
        script: |
          cd ios
          rm -rf Podfile.lock Pods
          pod deintegrate
          pod install --repo-update
          cd ..
      - name: iOS IPA Build
        script: |
          # Artık export_options.plist dosyası yerinde olduğu için hata vermeyecek
          flutter build ipa --release --export-options-plist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
