workflows:
  ios-workflow:
    name: Uluslararasi Alevi Vakfi iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    # HATANIN ÇÖZÜMÜ: Entegrasyonu buraya tanımladık
    integrations:
      app_store_connect: alevi-vakfi 
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter Paketlerini Yukle
        script: |
          flutter pub get
      - name: iOS Yapilandirma Dosyalarini Olustur (Kritik Adim)
        script: |
          # Windows'ta oluşmayan dosyaları sunucuda yoktan var eder
          flutter build ios --config-only
      - name: CocoaPods Kurulumu (Temiz Build)
        script: |
          cd ios
          # Hatalı bağlantıları temizleyip modern Swift ayarlarını kurar
          rm -rf Podfile.lock Pods
          pod install --repo-update
          cd ..
      - name: iOS IPA Build
        script: |
          # Release modunda derleme yaparak performansı artırıp crash riskini bitirir
          flutter build ipa --release --export-options-plist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
