platform :ios, '14.0' # iOS sürümünü 14'e sabitledik

prepare_command = "ruby -e \"require 'fileutils'; FileUtils.touch('Flutter/Generated.xcconfig')\""

target 'Runner' do
  use_frameworks! # Swift eklentileri (Hive/Path Provider) için bu şart!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Derleme hatalarını önlemek için standart ayarlar
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end